### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#27]
@aimalz I'll do this - it'll involve moving all our docs to a 'docs' folder and then getting readthedocs working. Feel free to ask questions about each line in your code review! :-)

**Comment by drphilmarshall** [comment]
@aimalz Since #28 we have a reasonable first set of docs, except that the `pdf` automodule command is yielding no output.

Browsing the [rtd documentation](http://docs.readthedocs.io/en/latest/builds.html#understanding-what-s-going-on) it seems that the problem might be the `import qp` line in `pdf.py`: by default, readthedocs does not install packages. Can you please enable the _Install Project_ option on the readthedocs `qp` project dashboard? That should fix it I think. Or at least, I hope! :-)

**Comment by aimalz** [comment]
Indeed, that fixed the problem!

**Comment by drphilmarshall** [comment]
Excellent!
