### ISSUE TITLE
Start LSST DESC Note

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#39]
Let's start an [LSST DESC Note]() writing up the `qp` code and some interesting tests, from the comprehensive suite in #36.  Since LSST DESC Notes can be IPython notebooks it should be easy to make code development and testing EQUAL to LSST DESC Note production :-) This issue can be closed once we have run `start_paper` and scrubbed the `ipynb` template of all guideline text.

**Comment by aimalz** [comment]
Let's make this a LaTeX-style LSST-DESC Note so it can be more easily adapted into a submittable paper.

**Comment by drphilmarshall** [comment]
OK! We can close this once we have run the cookiecutter and put in section headings with very rough, very terse notes on what needs to go in each section.

**Comment by drphilmarshall** [comment]
Looks like [`main.tex` in the `issue/39/start_paper` branch](https://github.com/aimalz/qp/blob/issue/39/start_paper/docs/desc-0000-qp-photo-z_approximation/main.tex) is pretty close to satisfying this issue. We talked about focusing on an LSST dataset from Sam rather than SDSS, but otherwise the section headings look sensible. Start the PR and request a review whenever you're ready, @aimalz ! :-)
