### ISSUE TITLE
Make first "Release"

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#40]
@aimalz Once you have closed #34 by merging #37 you should make our first "release", here:

https://github.com/aimalz/qp/releases

I'd suggest "v0.1 beta" as a reasonable name - and you can edit the release text once you have made it. Probably this should be a "pre-release" as well - we can save the "release" name for v1.0, after we've done an investigation of the quantile idea. What do you think? This could be the last issue of our "Launch" milestone :-)

**Comment by aimalz** [comment]
Done!
