### ISSUE TITLE
KLD notebook completion

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#41]
Hey @aimalz - Looks like there could be some inconsistencies in [the KLD notebook](http://htmlpreview.github.io/?https://github.com/aimalz/qp/blob/html/kld.html), between the precision and tension parts, and then the math and the plots.

Some suggestions:

* Go back and clean up the precision derivation to make it much more concise, but double check the steps to make sure the formula is correct. There could be an error of a  factor of 2 in there - and maybe some r vs 1/r confusion.

* Derive the full formula in terms of r and t first, and then simplify it to the two cases (zero-tension precision, r=1 tension) to recover the simpler approximate models.

* Overlay the full analytic formula on both plots as dotted black lines, as well as the approximate models in wide gray lines.

Then, I think we could add some insight in the conclusions, by pointing out where the two limits  (zero-tension precision, r=1 tension) might occur in practice. I guess the former is more like the photo-z PDF characterization problem? And the latter more like the case where an unknown systematic afflicts your cosmological parameter central value but not its uncertainty?

**Comment by aimalz** [comment]
Excellent points!  I've modified the notebook over on https://github.com/aimalz/qp/tree/issue/41/kld.  I'm not sure I sufficiently addressed your last suggestion of some applications relevant to photo-zs.  Thoughts?

**Comment by drphilmarshall** [comment]
Happy New Year, @aimalz! :-) I think the `kld` notebook is in pretty good
shape, modulo the following concerns:

* The "Precision" and "Tension" subsections have some small errors on them
- you should check that the definitions are correct and explained properly,
and that you explain clearly which limits (eg sigma >> sigm0, mu -> mu0,
etc) you are taking and why. I think the "precision" quantity should be
`sigma / sigma_0` and be called the "precision ratio", so that moving from
a broad prior to a narrow posterior involves a large positive precision
ratio (ie an increase in precision).

* When discussing the photo-z situations, you should explicit ly point out
which limits and which approximations hold.

**Comment by aimalz** [comment]
I think this was addressed a while back but we forgot to close the issue.
