### ISSUE TITLE
Survey mode

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#43]
`qp` should be tested on surveys of PDFs in addition to its current functionality with individual PDFs.  New tests for this capability will have to be written.

- [ ] #48 
- [ ] #74

**Comment by aimalz** [comment]
Also, this should include file i/o support, now #48.

**Comment by aimalz** [comment]
Also, there should be a demo notebook!

**Comment by aimalz** [comment]
For completeness, I'm noting that I started this issue planning to more or less copy the code I wrote [here](https://github.com/aimalz/chippr/blob/master/chippr/catalog.py) for CHIPPR (with a vague intention to eventually have CHIPPR rely on qp for that functionality), but I'm now rethinking how I might want a `catalog` object to be used (or really, how someone else might want to interact with one).

**Comment by aimalz** [comment]
I'm going to revive this to make it easier to write a script using the infrastructure of #70.  My intention is for this script to run the n(z) metrics on increasing numbers of galaxies to establish a scaling relation in resource requirements.  Sound good, @drphilmarshall?

**Comment by drphilmarshall** [comment]
Sounds good!
