### ISSUE TITLE
GMM fits

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#51]
In order to implement the suggestion from #36, `qp` will need the ability to perform a parametric fit to samples (particularly a Gaussian mixture model), rather than just obtaining a KDE and interpolating to convert between parametrizations.

**Comment by drphilmarshall** [comment]
Good idea to keep in mind wanting to do a more general parametric fit in future, but for now, how about we focus on getting `qp` PDF objects to fit themselves with GMMs, with an `Ncomponent=5` kwarg? We'll need this to make mock data based on an existing zs-zp dataset.
