### ISSUE TITLE
LSST SRD photo-z metrics

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#53]
Here's what the [LSST Science Requirements Document](https://docushare.lsstcorp.org/docushare/dsweb/Get/LPM-17/LSSTSRD_v5%202%203.pdf) has to say (in section 2.1) about photometric redshifts:

>  LSST will measure the comoving distance as a function of redshift in the redshift range 0.3–3.0 with an accuracy of 1-2%, and separately the growth of cosmic mass structure. A sample of about four billion galaxies with sufficiently accurate photometric redshifts is required. In order to achieve this comoving distance accuracy, the photometric redshifts requirements for this i < 25 flux-limited galaxy sample are i) the rms (σ) for error in (1 + z) must be smaller than 0.02, ii) the fraction of 3σ (“catastrophic”) outliers must be below 10%, and iii) the bias must be below 0.003.

So, we should somehow see that rms precision and low outlier rate in the simulated dataset the PZ WG provide. I guess the main thing for us is to quantify the additional rms error and bias introduced by using an approximation for each p(z).

**Comment by aimalz** [comment]
We can do this via moments (i.e. the difference between the first moment and the spectroscopic redshift).

**Comment by aimalz** [comment]
I think this is outside the scope of qp itself and can be implemented in one of the PZ WG scripts that calls qp, so I'm closing the issue.
