### ISSUE TITLE
Mock catalog construction

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#55]
* 10^5 galaxies with z_p, sigma_p, z_s
* follow the [XDGMM demo](https://github.com/tholoien/XDGMM/blob/master/Notebooks/Demo.ipynb) to make 2D GMM, using BIC to choose Ng (might need to provide some nominal sigma_s as well)
* draw samples from 2D GMM to check that it looks like the input data
* condition on each z_s to make the "true" PDFs (each one is also an Ng-component GMM)
* export via #48 in the #51 format

**Comment by aimalz** [comment]
Let's revise this plan now that we have mock data in the form of gridded photo-z PDFs from @MelissaGraham:

* read in the gridded photo-z PDFs via #60
* convert them to the GMM format via #51 
* save them via #48 

Then, we can address #56!

**Comment by drphilmarshall** [comment]
Bonza. Let's think about whether we can skip the GMM step, even, and treat
a 349-point grid as being finely enough sampled to be treated as "perfect"

**Comment by aimalz** [comment]
Unfortunately, the `qp.PDF.quantize()` function currently only works if there is a parametric `qp.PDF.truth` object to start from.  I suppose I could (and maybe should) change that, but I think it would be easier and no less principled to prep the data differently -- it's just a choice about whether this conversion happens within `qp` or as part of preparing the inputs.

**Comment by drphilmarshall** [comment]
OK, cool. Maybe give it a try fitting a GMM then, and see how we go.
Looking fwd to seeing the demo notebook!

**Comment by aimalz** [comment]
Oops, I forgot something important from the plan above!  Step zero needs to be to address #43.  So there are four issues standing between us and a notebook properly processing the data. . .

**Comment by drphilmarshall** [comment]
Actually if I were you I'd start a notebook to do _one_ GMM approximation, of one of the BPZ p(z)'s, and then think about catalog functionality. It's usually best to _jump on the data_ because it will inspire you in ways you haven't foreseen. To put it another way, you'll think better about how you want to implement catalogs _after_ you have started working with the catalog data. Do #51 before #43 ! :-)

**Comment by aimalz** [comment]
I think this is no longer a priority in light of the two sources of realistic photo-z PDFs, so I'm closing this issue.
