### ISSUE TITLE
Metric analysis

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#57]
* read in parametrized catalogs via #56 
* loop over N_metrics, N_floats, N_parametrizations
* plot the results

**Comment by drphilmarshall** [comment]
Let's make a new notebook, `data_analysis` and use the `Ensemble` class to analyze all of Melissa's PDFs.

**Comment by aimalz** [comment]
I'm going to use this issue to group together issues for specific metrics, namely #47, #49, and #42.  As `qp` will be the backend for the [LSST-DESC PZ DC1 paper](https://github.com/LSSTDESC/PZDC1paper), it will need to have the following metrics implemented in the `qp.Ensemble` class: 
- [x] RMSE (#9)
- [x] KLD (#9)
- [ ] KS/AD/CvM (#47)
- [ ] QQ (#42)
(Is the plan still to do all of these @sschmidt23?)
Some of these may require `qp` to have some notion of the true redshift, which is also a requirement of #53 (which in turn suggests #49).

**Comment by aimalz** [comment]
Update: I'm pretty happy with the status of [`issue/57/analysis`](https://github.com/aimalz/qp/tree/issue/57/analysis) and will run something like [the analysis notebook](https://github.com/aimalz/qp/blob/issue/57/analysis/docs/desc-0000-qp-photo-z_approximation/research/analysis.ipynb) on NERSC as soon as it's back on line.
