### ISSUE TITLE
Data exploration notebook

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#64]
This needs its own branch, so it merits its own issue.

**Comment by aimalz** [comment]
In making this notebook, I've discovered a "bug" in that the data we've been given is not normalized.  I think I need to know more about how it was made, but for now I'm implementing a kludge to normalize all parametrizations before plotting them.

**Comment by drphilmarshall** [comment]
Good plan. All PDF's must integrate to one!

**Comment by aimalz** [comment]
One thing we never implemented in pdf.py is integration of each parametrization, so we can't normalize them within qp.  I don't think this is necessarily a problem, but I'll write a disclaimer into the documentation saying users are responsible for making sure inputs integrate to unity.

**Comment by aimalz** [comment]
Also, the current holdup with this issue is that the mixture models fit to the samples from the real gridded data break the CDF/PPF functions.  I'm investigating where the problem is. . .

**Comment by drphilmarshall** [comment]
Some parametrizations are already normalized or normalizable, though,
right? If you can rejection sample then the PDF must be normalized! :-)

Re: mixture model bug: happy hunting! :-)

**Comment by aimalz** [comment]
I ran your analysis function for different numbers of parameters in each parametrization and got this cool result.  Check it out!  (-:
![money](https://cloud.githubusercontent.com/assets/8606810/24876046/2cd76f38-1df8-11e7-8603-3a653e462c66.png)
So it looks like with more than about 30 numbers for KLD and 100 for RMSE, it doesn't matter what parametrization you use.  But the KLD indicates samples are better than histograms are better than quantiles for fewer than 30 parameters and the RMSE indicates quantiles are better than samples are better than histograms for nontrivial numbers of parameters less than 30.  And at the smallest numbers of parameters, both metrics agree samples are better than histograms are better than quantiles.

**Comment by drphilmarshall** [comment]
Nice! Not sure what to make of the disagreements between KLD and RMSE,
other than to note that they motivate our switching to science-based
metrics (like ability to predict n(z)). I'd be interested to see how well
n(z) can be estimated by concatenating the samples and then histogramming
them, rather than stacking the KDEs. Want to have a go at that?

**Comment by aimalz** [comment]
Yep, here's the result:
![summary](https://cloud.githubusercontent.com/assets/8606810/24926501/c8073868-1ec9-11e7-9bcb-c7c73f304be8.png)
The high variability makes me think we're suffering from small number statistics here.  
But, when I inspect the n(z) for each parametrization, it's clear that there's a bug:
![nz_comparison](https://cloud.githubusercontent.com/assets/8606810/24926541/f8c2689c-1ec9-11e7-9a52-64f769510653.png)
I'm looking into it now. . .

**Comment by aimalz** [comment]
I think both issues (at N_floats=3 an N_floats=30) are being caused by not enforcing normalization for interpolations.  I made #72 and will fix that in a branch off of `issue/64/data_exploration_notebook`.  Stay tuned for a pull request!

**Comment by drphilmarshall** [comment]
Good. Those look like useful diagnostic plots to remake. Good luck!
