### ISSUE TITLE
Extrapolation of probability may break normalization

### ISSUE THREAD

**Issue by sschmidt23** [aimalz/qp#87]
The update to fill_value and extrapolation in the initialization of using='gridded' pdfs (that I believe was added because the default is 'NaN' outside the range of support I raised in an earlier issue) may cause problems in the normalization of the PDF if that range that you are normalizing extends beyond the grid points.  The line in question in qp.pdf.approximate:
 self.interpolator = spi.interp1d(x, y, kind=self.scheme, fill_value="extrapolate")

An example of the issue: I created a PDF ensemble object for a set of galaxies with p(z) evaluated on np.arange(0.005,2.11,0.01), so the lowest redshift point is 0.005, not 0.0.  The normalization in the initialization:
 self.gridded = qp.utils.normalize_integral(qp.utils.normalize_gridded(gridded, vb=vb))
normalizes between zmin and zmax.  However, if the p(z) value at z=zmin is non-zero, qp.pdf.approximate will extrapolate a non-zero value at z=0.0, so if you integrate qp.pdf.integrate(limits=(0.0,2.0)) you get a value >1.0, because approximate has extrapolated non-zero probability at z=0.0.

Is it smarter to set fill_value=0.0, rather than "extrapolate" in interp1d?  That seems to be the more sensible choice here, since presumably the PDF is zero outside the tested range over which it was initially normalized.  bounds_error=False will also need to be set.  This fix works on my local copy of qp.

**Comment by aimalz** [comment]
I've been focusing on improving quantile and sample interpolation for the past couple weeks (sloppily in [this dev branch](https://github.com/aimalz/qp/tree/issue/86/desc_revision)) while totally neglecting this problem with grid interpolation.  Thanks for catching it!  Your fix is now in the dev branch, and I'll try to get it into the master branch this week.
